apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: zenbakien-sorkuntza
  name: zenbakien-sorkuntza
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: zenbakien-sorkuntza
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: zenbakien-sorkuntza
    spec:
      containers:
      - env:
        - name: CUSTOMIZATION
          value: '{"type": "random", "firstvalue": 3}'
        - name: OUTPUT
          value: zenbakien-prozesamendua
        - name: OUTPUT_PORT
          value: "6000"
        - name: SERVICE
          value: IntegerValue
        image: ekhurtado/gcis:zenbakien-sorkuntza
        imagePullPolicy: Always
        name: zenbakien-sorkuntza
        ports:
        - containerPort: 7000
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
