apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aplikazio-kontroladore-baimenak
rules:
- apiGroups: ["ehu.gcis.org"]
  resources: ["applications", "applications/status"]
  verbs: ["get", "list", "watch", "patch"]
- apiGroups: ["ehu.gcis.org"]
  resources: ["microservices"]
  verbs: ["post", "put", "patch", "create", "update", "delete"] #No estoy seguro de que estos sean los verbos que hay que usar.
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["post", "put", "patch", "create", "update"]
- apiGroups: [""]
  resources: ["events", "configmaps", "services"]
  verbs: ["watch", "create", "update", "get", "patch"]