apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mikrozerbitzu-kontroladore-baimenak
rules:
- apiGroups: ["ehu.gcis.org"]
  resources: ["microservices", "microservices/status", "applications/status"]
  verbs: ["get", "list", "watch", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["post", "put", "patch", "create", "update", "delete"] #Julen: No estoy seguro de que estos sean los verbos que hay que usar.
- apiGroups: ["apps"]
  resources: ["deployments/status"]
  verbs: ["get", "list", "watch", "delete"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["post", "put", "patch", "create", "update"]
- apiGroups: [""]
  resources: ["events", "services"]
  verbs: ["watch", "create", "delete", "get"]