apiVersion: ehu.gcis.org/v1alpha1
kind: Application
metadata:
  name: nire-aplikazioa
spec:
  components: 
    - name: zenbakiensorkuntza
      service: BalioDezimalak
      image: ekhurtado/gcis:zenbakien-sorkuntza
      customization: '{"custom_mota": "goranzkoa", "custom_hasierakobalioa": 5}'
      outPort:
        name: zenbakiensorkuntza-oport
        dataType: TZenbaki
        protocol: HTTP
    - name: zenbakienprozesamendua
      service: BalioaBiderkatu
      image: ekhurtado/gcis:zenbakien-prozesamendua
      customization: '{"custom_biderkatzailea": 2.5}'
      inPort:
        name: zenbakienprozesamendua-iport
        dataType: TZenbaki
        protocol: HTTP
        number: '6000'
      outPort:
        name: zenbakienprozesamendua-oport
        dataType: TZenbaki
        protocol: HTTP
    - name: zenbakienaurkezpena
      service: GordeTXT
      image: ekhurtado/gcis:zenbakien-aurkezpena
      customization: '{"custom_fitxategiizen": "datuak.txt"}'
      inPort:
        name: zenbakienaurkezpena-iport
        dataType: TZenbaki
        protocol: HTTP
        number: '7000'
  channels: 
    - from: zenbakiensorkuntza-oport
      to: zenbakienprozesamendua-iport
    - from: zenbakienprozesamendua-oport
      to: zenbakienaurkezpena-iport