apiVersion: ehu.gcis.org/v1alpha1
kind: Application
metadata:
  name: nire-app
spec:
  components: 
    - name: creating-numbers
      service: NaturalValue
      image: gcr.io/gcis/creating-numbers:latest
      customization: '{"type": "Random", "firstvalue": 16}'
      outPort:
        name: naturalvalue-oport
        dataType: TNumber
        protocol: HTTP
    - name: processing-numbers
      service: IncreaseValue
      image: gcr.io/gcis/processing-numbers:latest
      customization: '{"step": 2}'
      inPort:
        name: increasevalue-iport
        dataType: TNumber
        protocol: HTTP
        number: '6000'
      outPort:
        name: increasevalue-oport
        dataType: TNumber
        protocol: HTTP
    - name: show-numbers
      service: ConsoleDisplay
      image: gcr.io/gcis/show-numbers:latest
      inPort:
        name: consoledisplay-iport
        dataType: TNumber
        protocol: HTTP
        number: '7000'
  channels: 
    - from: naturalvalue-oport
      to: increasevalue-iport
    - from: increasevalue-oport
      to: consoledisplay-iport