apiVersion: ehu.gcis.org/v1alpha1
kind: Application
metadata:
  name: nire-fog-aplikazioa-2
spec:
  microservices: 
    - name: zenbakiensorkuntza
      service: BalioOsoak
      image: ekhurtado/gcis:zenbakien-sorkuntza
      customization: '{"custom_mota": "goranzkoa", "custom_hasierakobalioa": 6}'
      outPort:
        name: zenbakiensorkuntza-oport
        dataType: TZenbaki
        protocol: HTTP
    - name: zenbakienprozesamendua
      service: BalioaBiderkatu
      image: ekhurtado/gcis:zenbakien-prozesamendua
      customization: '{"custom_biderkatzailea": 7}'
      inPort:
        name: zenbakienprozesamendua-iport
        dataType: TZenbaki
        protocol: HTTP
        number: '6500'
      outPort:
        name: zenbakienprozesamendua-oport
        dataType: TZenbaki
        protocol: HTTP
    - name: zenbakienaurkezpena
      service: GordeTXT
      image: ekhurtado/gcis:zenbakien-aurkezpena
      customization: '{"custom_fitxategiizen": "datuak.txt"}'
      inPort:
        name: zenbakienaurkezpena-iport
        dataType: TZenbaki
        protocol: HTTP
        number: '7500'
  channels: 
    - from: zenbakiensorkuntza-oport
      to: zenbakienprozesamendua-iport
    - from: zenbakienprozesamendua-oport
      to: zenbakienaurkezpena-iport