apiVersion: ehu.gcis.org/v1alpha1
kind: Application
metadata:
  name: NumbersProcessing
spec:
  components: 
    - name: CreatingNumbers
      service: NaturalValue
      image: gcr.io/gcis/processing-numbers:latest
      customization: '{"type": "random"}'
      outPort:
        name: CreatingNumbersOPort
        dataType: TNumber
        protocol: HTTP
    - name: ProcessingNumbers
      service: IncreaseValue
      image: gcr.io/gcis/processing-numbers:latest
      customization: '{"step": 2}'
      inPort:
        name: ProcessingNumbersIPort
        dataType: TNumber
        protocol: HTTP
        number: '6000'
      outPort:
        name: ProcessingNumbersOPort
        dataType: TNumber
        protocol: HTTP
    - name: ShowNumbers
      service: ConsoleDisplay
      image: gcr.io/gcis/processing-numbers:latest
      inPort:
        name: ShowNumbersIPort
        dataType: TNumber
        protocol: HTTP
        number: '7000'
  channels: 
    - from: CreatingNumbersOPort
      to: ProcessingNumbersIPort
    - from: ProcessingNumbersOPort
      to: ShowNumbersIPort