apiVersion: ehu.gcis.org/v1alpha1
kind: Application
metadata:
  name: NumbersProcessing
spec:
  channels:
  - from: CreatingNumbersOPort
    to: ProcessingNumbersIPort
  - from: ProcessingNumbersOPort
    to: ShowNumbersIPort
  components:
  - customization: '{"type": "random"}'
    image: gcr.io/gcis/processing-numbers:latest
    name: CreatingNumbers
    outPort:
      dataType: TNumber
      name: CreatingNumberOPort
      protocol: HTTP
    service: NaturalValue
  - customization: '{"step": 2}'
    image: gcr.io/gcis/processing-numbers:latest
    inPort:
      dataType: TNumber
      name: ProcessingNumbersIPort
      number: '6000'
      protocol: HTTP
    name: ProcessingNumbers
    outPort:
      dataType: TNumber
      name: ProcessingNumbersOPort
      protocol: HTTP
    service: IncreaseValue
  - image: gcr.io/gcis/processing-numbers:latest
    inPort:
      dataType: TNumber
      name: ShowNumberIPort
      number: '7000'
      protocol: HTTP
    name: ShowNumbers
    service: ConsoleDisplay
