apiVersion: v1
kind: PersistentVolume
metadata:
  name: nodered-data
  labels:
    type: local
spec:
  storageClassName: nodered-data
  capacity:
    storage: 800Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/nodered/data"