apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: node-red-data
  name: node-red-data
spec:
  storageClassName: nodered-data
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
status: {}
